apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  # Note: persistent-volumes.yaml excluded - PVs should be created once and not managed by Tilt
  # They have Retain policy and can't be easily deleted when bound to PVCs
  # Create them manually: kubectl apply -f k8s/scheduling/persistent-volumes.yaml
  - claims.yaml
  - faktory.yaml

