apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - namespace.yaml
  - prometheus.yaml
  - loki.yaml
  - otel-collector.yaml
  - grafana.yaml

configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml=prometheus-k8s.yml
    options:
      disableNameSuffixHash: true
  - name: loki-config
    files:
      - config.yml=loki-k8s-config.yml
    options:
      disableNameSuffixHash: true
  - name: otel-collector-config
    files:
      - config.yaml=otel-collector-config.yml
    options:
      disableNameSuffixHash: true
  - name: grafana-datasources
    files:
      - datasources.yaml=grafana-datasources.yml
    options:
      disableNameSuffixHash: true
